export enum SOCKET_CLIENT_TO_SERVER {
  "ROOM_PLAYER_JOIN" = "ROOM_PLAYER_JOIN",
  "ROOM_PLAYER_LEAVE" = "ROOM_PLAYER_LEAVE",
}

export enum SOCKET_SERVER_TO_CLIENT {
  "PAGE_JOINED" = "PAGE_JOINED",
  "ROOM_PLAYER_JOINED" = "ROOM_PLAYER_JOINED",
  "ROOM_PLAYER_LEFT" = "ROOM_PLAYER_LEFT",
}
